### PR TITLE
Patch for issue #692

### PR DESCRIPTION
**Pull request by anindex**
This PR proposes bug fix for issue #692 by adding explicitly SizeType and IndexType into template arguments when initializing patttern_t in StoreHDF read and write.

### CODE REVIEW

**Review by devreal — APPROVED** [review]

**Comment by devreal** [comment]
@anindex Do I understand your commits right that HDF5 is not enabled in CI? It would be nice to have a test case for reported issue somewhere. I believe there is a dedicated set of HDF5 tests.

**Comment by anindex** [comment]
I will write a test case for HDF5 read and write in other PR, for now, I will keep this fix minimal :)

**Comment by devreal** [comment]
Looking at the patch again I realized that it fixes the *symptoms* of the problem (a type-mismatch in the HDF5 driver) but eventually we should address the underlying issues of the DASH types being inflexible with regard to the types they accept. `TilePattern` should, for example, have a c'tor templated on the type of `SizeSpec` and convert it if necessary. Maybe that will come as a byproduct of the pattern test suite :)

**Comment by devreal** [comment]
Also: the codecov CI seems broken. Merging anyway.

**Pull request merged**
