### PR TITLE
Fixes #466: icc cannot compile

### LINKED ISSUE #466: Intel 2018 can't compile halo-stencil example
With Intel 2018.1.163 i get these errors for `ex.11.halo-stencil`:

```
-- DASH version 0.3.0
-- -----------------------------------------------------------
-- Install prefix:           (INSTALL_PREFIX)                 /home/wesarg/opt/dash-0.3.0/
-- Build type:               (CMAKE_BUILD_TYPE)               Release
-- Generic build:            (BUILD_GENERIC)                  OFF
-- Build shared libraries:   (BUILD_SHARED_LIBS)              OFF
-- Host system identifier:   (ENVIRONMENT_TYPE)               default
-- Strict compiler warnings: (ENABLE_DEV_COMPILER_WARNINGS)   OFF
-- Style compiler warnings:  (ENABLE_EXT_COMPILER_WARNINGS)   OFF
-- Link Time Optimization:   (ENABLE_LT_OPTIMIZATION)         OFF
-- Compiler reports:         (ENABLE_CC_REPORTS)              OFF
-- Compile time reduction:   (ENABLE_COMPTIME_RED)            OFF
-- Debug log messages:       (ENABLE_LOGGING)                 OFF
-- Trace log messages:       (ENABLE_TRACE_LOGGING)           OFF
-- DART log messages:        (ENABLE_DART_LOGGING)            OFF
-- Runtime assertions:       (ENABLE_ASSERTIONS)              ON
-- Unified RMA memory model: (ENABLE_UNIFIED_MEMORY_MODEL)    ON
-- MPI shared windows:       (ENABLE_SHARED_WINDOWS)          ON
-- MPI dynamic windows:      (ENABLE_SHARED_WINDOWS)          ON
-- Enable multithreading:    (ENABLE_THREADSUPPORT)           ON
-- Default index type long:  (ENABLE_DEFAULT_INDEX_TYPE_LONG) ON
-- libnuma support:          (ENABLE_LIBNUMA)                 ON
-- hwloc support:            (ENABLE_HWLOC)                   ON
-- hwloc PCI support:        (ENABLE_HWLOC_PCI)               ON
-- PAPI support:             (ENABLE_PAPI)                    OFF
-- MKL support:              (ENABLE_MKL)                     OFF
-- BLAS support:             (ENABLE_BLAS)                    OFF
-- LAPACK support:           (ENABLE_LAPACK)                  OFF
-- ScaLAPACK support:        (ENABLE_SCALAPACK)               OFF
-- PLASMA support:           (ENABLE_PLASMA)                  OFF
-- HDF5 support:             (ENABLE_HDF5)                    OFF
-- Enabled DART backends:    (DART_IMPLEMENTATIONS)           mpi
-- C   compiler id:          Intel
-- C++ compiler id:          Intel
-- MPI implementation:       intelmpi
-- PAPI                      disabled
-- MKL                       disabled
-- BLAS                      disabled
-- hwloc                     enabled
-- likwid                    disabled
-- LAPACK                    disabled
-- ScaLAPACK                 disabled
-- PLASMA                    disabled
-- HDF5                      disabled
-- libnuma                   enabled
```
```
[ 49%] Building CXX object dash/CMakeFiles/ex.11.halo-stencil.mpi.dir/examples/ex.11.halo-stencil/main.cpp.o
cd /home/wesarg/scratch/build-dash/dash && /sw/global/compilers/intel/2018/compilers_and_libraries_2018/linux/bin/intel64/icpc   -I/home/wesarg/DASH/dash/dash/include -I/home/wesarg/DASH/dash/dash/src -I/home/wesarg/DASH/dash/dart-if/include -I/sw/taurus/libraries/openmpi/2.1.0-intel/include -I/home/wesarg/scratch/build-dash/gtest/src/GTestExternal/googletest/include  -DDART_HAVE_SYNC_BUILTINS -pthread -DDART_HAVE_PTHREADS -O3 -DNDEBUG  -xhost -std=c++11 -qopenmp    -Ofast -DDASH_RELEASE -DDASH_ENABLE_ASSERTIONS -DDART_ENABLE_ASSERTIONS    -DDASH -DDASH_ENABLE_DEFAULT_INDEX_TYPE_LONG -DDASH_ENABLE_THREADSUPPORT -DDASH_ENABLE_UNIFIED_MEMORY_MODEL -DDASH_ENABLE_TEST_LOGGING -DDASH_ENABLE_HWLOC -DDASH_ENABLE_NUMA -DDASH_ENV_HOST_SYSTEM_ID='default' -qopenmp -Wno-sign-compare -DMPI_IMPL_ID='intelmpi' -Wno-unused -std=gnu++11 -o CMakeFiles/ex.11.halo-stencil.mpi.dir/examples/ex.11.halo-stencil/main.cpp.o -c /home/wesarg/DASH/dash/dash/examples/ex.11.halo-stencil/main.cpp
/home/wesarg/DASH/dash/dash/include/dash/halo/iterator/HaloMatrixIterator.h(160): error: no operator "[]" matches these operands
            operand types are: std::initializer_list<std::array<dash::default_index_t, 2UL>> [ int ]
        halo_coords[d] += stencil[d];
                   ^
          detected during instantiation of "ElementT dash::HaloMatrixIterator<ElementT, PatternT, StencilSpecT, Scope>::value_at(dash::HaloMatrixIterator<ElementT, PatternT, StencilSpecT, Scope>::region_index_t) [with ElementT=element_t={unsigned char}, PatternT=Pattern_t, StencilSpecT=StencilSpec_t, Scope=dash::StencilViewScope::BOUNDARY]" at line 157 of "/home/wesarg/DASH/dash/dash/examples/ex.11.halo-stencil/main.cpp"

/home/wesarg/DASH/dash/dash/include/dash/halo/iterator/HaloMatrixIterator.h(161): error: no operator "[]" matches these operands
            operand types are: std::initializer_list<std::array<dash::default_index_t, 2UL>> [ int ]
        if(halo_coords[d] < 0 || halo_coords[d] >= _haloblock.view().extent(d))
                      ^
          detected during instantiation of "ElementT dash::HaloMatrixIterator<ElementT, PatternT, StencilSpecT, Scope>::value_at(dash::HaloMatrixIterator<ElementT, PatternT, StencilSpecT, Scope>::region_index_t) [with ElementT=element_t={unsigned char}, PatternT=Pattern_t, StencilSpecT=StencilSpec_t, Scope=dash::StencilViewScope::BOUNDARY]" at line 157 of "/home/wesarg/DASH/dash/dash/examples/ex.11.halo-stencil/main.cpp"

/home/wesarg/DASH/dash/dash/include/dash/halo/iterator/HaloMatrixIterator.h(161): error: no operator "[]" matches these operands
            operand types are: std::initializer_list<std::array<dash::default_index_t, 2UL>> [ int ]
        if(halo_coords[d] < 0 || halo_coords[d] >= _haloblock.view().extent(d))
                                            ^
          detected during instantiation of "ElementT dash::HaloMatrixIterator<ElementT, PatternT, StencilSpecT, Scope>::value_at(dash::HaloMatrixIterator<ElementT, PatternT, StencilSpecT, Scope>::region_index_t) [with ElementT=element_t={unsigned char}, PatternT=Pattern_t, StencilSpecT=StencilSpec_t, Scope=dash::StencilViewScope::BOUNDARY]" at line 157 of "/home/wesarg/DASH/dash/dash/examples/ex.11.halo-stencil/main.cpp"

/home/wesarg/DASH/dash/dash/include/dash/halo/iterator/HaloMatrixIterator.h(167): error: no suitable user-defined conversion from "std::initializer_list<std::array<dash::default_index_t={dash::internal::default_signed_index={long}}, 2UL>>" to "std::array<dash::default_index_t={dash::internal::default_signed_index={long}}, 2UL>" exists
        return value_halo_at(halo_coords);
                             ^
          detected during instantiation of "ElementT dash::HaloMatrixIterator<ElementT, PatternT, StencilSpecT, Scope>::value_at(dash::HaloMatrixIterator<ElementT, PatternT, StencilSpecT, Scope>::region_index_t) [with ElementT=element_t={unsigned char}, PatternT=Pattern_t, StencilSpecT=StencilSpec_t, Scope=dash::StencilViewScope::BOUNDARY]" at line 157 of "/home/wesarg/DASH/dash/dash/examples/ex.11.halo-stencil/main.cpp"

compilation aborted for /home/wesarg/DASH/dash/dash/examples/ex.11.halo-stencil/main.cpp (code 2)
```

Any clues how to fix this?

### PR DESCRIPTION
**Pull request by rkowalewski**

### CODE REVIEW

**Comment by dhinf** [comment]
you were faster :)
I did nearly the same changes. 

I got a problem with onesided.h in dash/CMakeFiles/dash-test-mpi.dir/test/memory/GlobHeapMemTest.cc.o: 
Onesided.h(230): error: a constexpr function cannot have a nonliteral return type "void"
  void get_value(

Did you had the same error?

**Comment by dhinf** [comment]
Btw. it's interesting that gcc 7 doesn't found the obvious bug

**Comment by rkowalewski** [comment]
Ah OK. Sorry, Dennis. :) I needed a fix since I had to compile with icc anyway. However I didn't have this issue with `Onesided.h`. Maybe it is again a version-specific thing.

**Comment by dhinf** [comment]
Don't be sorry, i'm glad you did it. I used version icpc (ICC) 18.0.1 20171018

**Review by dhinf — APPROVED** [review]
Works for me. The issue with "void" as return type for constexpr is for c++11 only an issue. In C++14 void is a literal type.

**Pull request merged**
