### PR TITLE
Use a copy of MPI_COMM_WORLD to avoid conflicts on global collective operations

### PR DESCRIPTION
**Pull request by devreal**
The copy is named DART_COMM_WORLD and is meant for internal use only.

### CODE REVIEW

**Comment by fmoessbauer** [comment]
@devreal: CircleCI reports a segfault in the openmpi container.

**Comment by devreal** [comment]
Looking at it right now.

**Comment by devreal** [comment]
This is a nasty one, Valgrind reports:

```
==6151== Invalid free() / delete / delete[] / realloc()
==6151==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==6151==    by 0x70B1FC: dart__base__locality__delete (locality.c:246)
==6151==    by 0x6F6F19: dash::Team::unregister_team(dash::Team*) (Team.h:530)
==6151==    by 0x6F71F8: dash::Team::~Team() (Team.h:171)
==6151==    by 0x6B3FFF7: __run_exit_handlers (exit.c:82)
==6151==    by 0x6B40044: exit (exit.c:104)
==6151==    by 0x6B26836: (below main) (libc-start.c:325)
==6151==  Address 0x99cbe0 is 0 bytes inside data symbol "ompi_mpi_comm_null"
```

Not sure where `ompi_mpi_comm_null` comes from but I will make my way through it...

**Comment by devreal** [comment]
I think it is related to a incomplete move assignment/ctor of dash::Team, currently trying a fix.

**Comment by devreal** [comment]
OK, so the reason is that `DART_TEAM_NULL` (aka `-1`) is passed to `Team::unregister_team`, which then unconditionally calls `dart__base__locality__delete` on the DART team ID. I have not yet figured out where this null team comes from, the design is way too complex imo and there are `DART_TEAM_NULL` flying around everywhere. I already started getting rid of them where possible but I am not there yet. 

I think it has been pure luck this bug didn't show up earlier...

**Comment by devreal** [comment]
After half day of debugging this, I found the root cause of the problem: the fields `dash::Team::_team_null` and `dash::Team::_team_all` are _actually destructed on exit_, leading to a call to `Team::unregister_team` without checking for `DART_TEAM_NULL`, leading to `-1` being used as an index... This should be fixed now, along with some other things I came across on my journey. 

Nevertheless, I noticed another point: The way we currently use `dash::Team::_team_[null|all]` is dangerous since in several places they are passed as reference to the caller, i.e., `TeamLocality::team()`, who is then able to alter these teams. Of course, the user should not be able to alter these invariants! Fixing this is not easy, since pointers to Teams are used in several places. Ideally, these invariants would be `constexpr`, which is hard to do with the current implementation of the ctor...

**Comment by fmoessbauer** [comment]
Such a tiny change but this amount of debugging... Thank you for taking your time into this. :+1: I will make a separate ticket for refactoring and cleanup of `dash::Team`

**Pull request merged**
