### PR TITLE
Add information to BenchmarkParams

### PR DESCRIPTION
**Pull request by devreal**
This PR adds the current DASH version and git commit hash as well as the compiler version to the benchmark output. Having the git commit hash in the benchmark output is helpful to investigate possible performance regressions from older benchmark runs.

This PR also moves the definition of the DASH version to `dash/Version.h` and thus would supersede #608.

### CODE REVIEW

**Comment by devreal** [comment]
The version went back into the CMake file as it is needed for the doxygen documentation. The `Version.h` is now generated from the information in the CMake file (and the git hash was added there).

**Comment by fmoessbauer** [comment]
@fuerlinger : I suppose this change breaks your Makefiles. Can you provide an updated version?

**Comment by fuerlinger** [comment]
Yes, I'll update my makefiles. Should not be a problem.

**Comment by rkowalewski** [comment]
OK cool. Exactly what I need now for another benchmark session. :)

**Review by rkowalewski — APPROVED** [review]

**Comment by rkowalewski** [comment]
What is with this PR? Can we merge it?

**Comment by devreal** [comment]
Forgot to merge, done.

**Pull request merged**
