### PR TITLE
Feat docker prebuild

### PR DESCRIPTION
**Pull request by fmoessbauer**
For faster CI tests, we use prebuild docker containers from dockerhub `dashproject/ci-testing`. The containers stored there are build from the dockerfiles located in the dash project.

Currently they are automatically build from the git `fmoessbauer/dash` as docker does not detect the official dash repository. If a new container is needed or changes are necessary contact me.

### CODE REVIEW

**Comment by fuchsto** [comment]
That's cool, thank you! What's the problem with the dash-project/dash.git repository?
I have a bad feeling about coupling the CI build to a single person.

Also: It's "dash-project", not "dashproject".

Please post a link to the dockerhub page of the organization you created there.

**Comment by fmoessbauer** [comment]
Yes,... I have the same feeling. In dockerhub you can set hooks, that docker containers are build automatically on changes in a github repo. For that I founded the dashproject organisation which hold the ci-testing docker repository.

However docker does not detect the dash-project repositorys but only my public/private ones. Up to now I am not sure if this is a bug in dockerhub, not part of the free features, or if the dash organization on github does not allow this integration.

Maybe there is a permission request from docker to access dash still pending?

**Comment by fuchsto** [comment]
Ah, here it is: https://hub.docker.com/r/dashproject/ci-testing/

Add me as a member/admin of the organization, I'll have a look at this.
I tried to create the organization "dash-project" but dockerhub didn't allow it. No reason given, just turned the input field red.

My user name is "fuchsto".

**Comment by fmoessbauer** [comment]
Done. You are now in the owner group. I had the same problem, but simply "-" is not allowed in names... The dockerhub organization interface looks very half-baked to me.

**Comment by fmoessbauer** [comment]
Now the dash-repos are displayed, but whenever I try to setup a automated build, after clicking ok this message is shown:
`Could not find github repo dash-project/dash`

**Comment by fuchsto** [comment]
It's dash-project/dash.git perhaps? Where do you edit this? I can't find a way to specify a repo.

I approved the authorization request, there is not much more I could do in this respect.

**Comment by fmoessbauer** [comment]
Maybe, but I can't set the name manually.
Go to: Create (top right) -> create automated build -> Github -> dash-project -> dash -> Fill out form (dashproject/testing - public - description) -> Create

**Comment by fuchsto** [comment]
How about this:

https://forums.docker.com/t/cant-access-new-github-organization-for-automated-builds/1080/10

**Comment by fuchsto** [comment]
Ah, thanks. Done! The builds are currently queued:

https://hub.docker.com/r/dashproject/ci/builds/

Let's wait and see.

**Comment by fuchsto** [comment]
I found some organizations on dockerhub with "-" in their name. These are "official repositories" however.
See: https://docs.docker.com/docker-hub/official_repos/

So we should do that after the release I think.
Here is the list of requirements for "official repositories". Since our latest efforts, we satisfy all of them.

https://github.com/docker-library/official-images/blob/master/NEW-IMAGE-CHECKLIST.md
https://github.com/docker-library/official-images

**Comment by fuchsto** [comment]
Okay, builds on dockerhub succeeded:
https://hub.docker.com/r/dashproject/ci/builds/

Please change `dashproject/ci-testing` to `dashproject/ci` in configuration and delete the `dashproject/ci-testing` repository on dockerhub.

**Comment by fmoessbauer** [comment]
Cleanup done! You can merge.

**Pull request merged**
