### PR TITLE
Feat 52 nastympi

### PR DESCRIPTION
**Pull request by fmoessbauer**
Adresses #52

### CODE REVIEW

**Comment by fmoessbauer** [comment]
Finally drilled it down to a bug in NastyMPI when using gcc. See #52 for details. I fixed that in branch `NastyMPI/bug-gcc-macro` and now the CI works (but does not pass due to actual errors). However after that is finally fixed, we should pull from NastyMPI's master branch again.

**Comment by fuchsto** [comment]
@rkowalewski Also see my PR #189 which is more stable at this point.

**Comment by fmoessbauer** [comment]
Do we still need this PR? Aren't the changes already covered by the already merged PR #189 ?

**Comment by fuchsto** [comment]
Yes, we need this PR as it fixes the integration of NastyMPI.

**Comment by fmoessbauer** [comment]
Unfortunately we hit the memory limit on CircleCI (4 GB per container). However the memory dump looks highly suspicious to me, as the memory consumption of one mpi process is way higher than the others. For me, this indicates a memory leak. See this [memorydump](https://668-45930061-gh.circle-artifacts.com/0/tmp/memory-usage.txt).

| PID     | RSS/Memory  | %CPU  | COMMAND|
| ------- | ------- | --------- | ------------ |
| 21921 | 3591264 | 33.6 | dash-test-mpi |
| 21922 | 476232 | 71.2 | dash-test-mpi |
| 21923 | 475704 | 70.4 | dash-test-mpi |

**Comment by fuchsto** [comment]
Heh, looks like you found a memory leak in NastyMPI.
Your debugging-Fu was stronger than mine, I thought it was a corrupt free / bad malloc in finalization of NastyMPI.
I'll see if I can valgrind it out.

**Comment by rkowalewski** [comment]
I will have a look at this.

**Comment by rkowalewski** [comment]
@fuchsto @fmoessbauer After investing much time into these memory leaks and `MPI_Win_get_attr` errors after calling `MPI_Finalize` I have pinpointed and fixed it. Now the build looks good however the status is "TIMED OUT". I cannot really tell why but maybe the timeout in our CI scripts is too low? We may also reduce the NASTY_SLEEP_INTERVAL to 3 and try it again.

**Pull request merged**
