### PR TITLE
removed aritmetic operators in LocalMatrixRef

### PR DESCRIPTION
**Pull request by dhinf**

### CODE REVIEW

**Review by fmoessbauer — CHANGES_REQUESTED** [review]
See my comment in #381

**Comment by fmoessbauer** [comment]
Please review, as the process becomes useless if I review the changes myself.

**Comment by dhinf** [comment]
I would, but i'm not allowed.

**Comment by fmoessbauer** [comment]
@dhinf That's a pitty, I cannot assign you as a reviewer as this is your PR. Just write your comments here, or click on the Files Changed button and add inline comments. This should work.

**Comment by devreal** [comment]
Please do not review or merge as there will be changes coming from @fuchsto

**Comment by fmoessbauer** [comment]
I guess this one can be closed as this was already fixed by @devreal in #423.

**Comment by devreal** [comment]
Ahh sorry, totally forgot about this PR!

**Pull request closed without merging**
