### PR TITLE
Bug 140 dart memleaks

### PR DESCRIPTION
**Pull request by devreal**
Fix multiple memory leaks, including leaking `MPI_Group` handles and problems in `host_topology`.

### CODE REVIEW

**Comment by fuchsto** [comment]
@devreal Merging the current state of development into your branch should fix this.

**Comment by fuchsto** [comment]
@devreal 

Lots of much needed fixes, thanks!

What's with the TODO comment / question here:
https://github.com/dash-project/dash/pull/155/files#diff-94c24e191167fd4a413d88568786e406R139

I only refactored the parts in DART that I needed for my stuff in DASH, so I have no idea what's the
correct semantics here.
This is also why I don't like functions named "copy" in C and rather use "clone" or "assign" in interfaces (see `dart_locality.h`).
For "copy", there is no intuitive connotation of ownership semantics, either.

**Comment by fuchsto** [comment]
Fixes #140

**Comment by devreal** [comment]
@fuchsto: My todo was due to the fact that `dart_group_copy` only makes a shallow copy of the dart_group_t object (it does not duplicate the MPI group object). I thought that passing the same MPI group as input and output to `MPI_Group_union` is erroneous. However, I after re-thinking this it's OK. Deleted it in #160.

For your question in the same place: it's a global unit ID ;)

**Pull request merged**
