### PR TITLE
Fixes to dart_send/recv interface

### PR DESCRIPTION
**Pull request by devreal**
Improvements to dart_send/recv interface:
1. Add const qualifier
2. Check for integer overflow 
3. Fix documentation

### CODE REVIEW

**Comment by devreal** [comment]
Wrong base branch used, closing without merge. Please ignore.

**Comment by fuchsto** [comment]
Thanks, but don't put too much industry best practice into these functions yet, it's work in progress for an unrelated feature. Unblocking variants are also missing, etc.

**Comment by devreal** [comment]
I'm just trying to keep development (or at least the part I feel responsible for, DART) clean and avoid to have half-baked implementations of new features while working  towards a release. We should concentrate on getting the release done, not adding new features that require immediate fixing after the merge...

**Comment by fuchsto** [comment]
Rightly so.

**Pull request closed without merging**
