### PR TITLE
Leave context empty in single-argument DASH_LOG_* macros calls

### PR DESCRIPTION
**Pull request by devreal**
Otherwise messages without a context won't be printed...

### CODE REVIEW

**Comment by devreal** [comment]
Wow, the whole DASH code base is littered with `DASH_LOG_DEBUG("some string")` instances (who dafuq puts them in without needing them?!) so forcing a context explicitly would require fixing a gazillion places (as said before, there is no "quick fixing" here...) I will change the PR so that single messages are printed without context. I cannot currently push to Github, will try again later...

**Comment by devreal** [comment]
Wow, the whole DASH code base is littered with `DASH_LOG_DEBUG("some string")` instances (who dafuq puts them in without needing them?!) so forcing a context explicitly would require fixing a gazillion places (as said before, there is no "quick fixing" here...) I will change the PR so that single messages are printed without context. I cannot currently push to Github, will try again later...

**Comment by devreal** [comment]
Wow, the whole DASH code base is littered with `DASH_LOG_DEBUG("some string")` instances, none of which will ever have produced any output. Forcing a context explicitly would require me to fix a gazillion places (as said before, there is no "quick fixing" here...) I have changed the PR so that single messages are printed without context.

**Comment by devreal** [comment]
Ups, looks like Github had a hickup and posted my earlier message that it said cannot be posted...

**Review by dhinf — APPROVED** [review]
works for me.

**Pull request merged**
