### PR TITLE
Improvements to dash::Future

### LINKED ISSUE #416: Bulk wait for async copy
In the [hpccg](https://github.com/dash-project/dash-apps/blob/hpccg-coarray/hpccg/src_dash/exchange_externals.cpp#L69) benchmark the following is used to wait for a bulk of `dash::copy_async` transfers:

```c++
for(int i=0; i<num_neighbors; ++i) {
    int n_send = send_length[i];
    int neighbor = neighbors[i];
    int offset_at_neighbor = A->offset[i];
    dash::copy_async(send_buffer, send_buffer + n_send,
      narray.row(neighbor).begin() + A->offset[i]);
    send_buffer += n_send;
  }

  // wait for the transfer to complete
  narray.flush_all();
```

Is this a valid way to wait for the transfers? Otherwise I would have to use (e.g.) a `std::vector<VeryComplicatedType>` to store the futures. But as indicated, then the type of the vector might be very complicated, as `auto` cannot be used.

### PR DESCRIPTION
**Pull request by devreal**
This PR extends `dash::Future` to allow for a meaningful `test()` function and proper tear-down. The latter is required to avoid memory leaks if `dash::copy_async` uses handles and the user does not `wait()` on it. 

Fixes #416 
See also #447

### CODE REVIEW

**Review by fmoessbauer — COMMENTED** [review]
Your changes look good so far, however I have some concerns regarding the performance of multiple relatively small async copy calls. Are there already benchmark results comparing before and after? If not, we could easily use the DASH implementation of Cafbench therefor.

**Comment by devreal** [comment]
> Are there already benchmark results comparing before and after? If not, we could easily use the DASH implementation of Cafbench therefor.

I don't think we have a proper benchmark for it but it would be easy to create one. I might give it a try next week. 

However, I don't immediately see how we could improve performance without sacrificing features. The current implementation of `dash::Future` is very basic and fails a simple use-case like `while (fut.test()) do_something_else();`, not to mention the potential for memory leaks. 

I am open to ideas on how to save the dynamic allocation of the `std::vector` holding the handles (which probably is the critical addition in this PR).

**Comment by fuchsto** [comment]
Did not have a look at the implementation yet but the PR is a good catch.
More important than benchmarks for now: It's a new feature -> add unit tests!

**Comment by devreal** [comment]
@fuchsto Good point. Did that, made me change the implementation even more:

1. Made `dash::Future` non-copyable, similar to `std::future`. We might want to add `dash::SharedFuture` at some point but that's a different story.
2. Consolidated `dash::internal::copy_impl` and `dash::internal::copy_async_impl` into a single implementation to i) reduce duplicated code and ii) overlap the transfer to/from multiple remote units. There is still a metric ton of duplicated code in `Copy.h` but I didn't bother touching that as I expect it to change with #410 anyway. 
3. Added `dart_testall` and `dart_test`, which upon success also ensure remote completion if required.
4. All copy implementations now use handles: `dash::copy` waits for their (remote) completion while `dash::copy_async` puts them into a future. 
5. Handling of large transfers is now left to DART (see #434), slightly simplifying the code in `copy_impl`.

**Review by fmoessbauer — APPROVED** [review]
This PR looks good and IMO we can merge it. As the implementation of copy will change anyways I have no problem with using handles there. In the future we can improve that by providing optimized copy for tiny transfers.

The changes related to `dash::Future` are really good ones.

**Pull request merged**
