### PR TITLE
Feat hdf5 team

### PR DESCRIPTION
**Pull request by fmoessbauer**
Extends dash's hdf5 storage driver to support containers that are only allocated by a subset of units.

### CODE REVIEW

**Comment by fmoessbauer** [comment]
Currently blocked due to #126 and #125

**Comment by fuchsto** [comment]
@fmoessbauer Fixes for #125 and #126 have pull requests pending.

**Comment by fmoessbauer** [comment]
Still blocked due to PR #135.

**Comment by ddiefenthaler** [comment]
@fuchsto This pull request looks fine to me.
But I think a more experienced eye should also take a look.

**Pull request merged**
